# Site information
site_name: Afsprakenstelsel iWlz Netwerkmodel
site_url: https://istandaarden.github.io/Afsprakenstelsel-iWlz/

# Repository information
repo_url: https://github.com/iStandaarden/Afsprakenstelsel-iWlz
repo_name: iStandaarden/Afsprakenstelsel-iWlz

# Theme configuration
theme:
  name: material
  language: nl
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: custom
      accent: deep orange
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
      primary: custom
      accent: deep purple
  features:
      - navigation.top
      - navigation.sections
      # - navigation.instant
      - navigation.tracking
      - navigation.footer
      - navigation.tabs
      - navigation.expand
      - navigation.indexes
      - search.highlight
      - search.suggest
      - content.code.annotate
      - content.code.copy
      - content.tabs.link
      - content.tooltips
      - toc.follow

# Custom CSS
extra_css:
  - css/zin.css

# Markdown extensions
markdown_extensions: 
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


# Navigation structure
nav:
  - Welkom: index.md
  - Inleiding:
      - inleiding/index.md 
  - Organisatiebeleid:
      - organisatiebeleid/index.md
  - Proces:
      - proces/index.md
  - Applicatie: 
      - applicatie/index.md
      - Applicatiecomponenten: applicatie/applicatiecomponenten.md
      - Diensten: 
          - applicatie/diensten/index.md
          - Notificeren en Melden: applicatie/diensten/notificeren-en-melden.md
